mkdir fedtask

# cifar10_resnet9_clustered_N10_K10 - quantitative
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K10 --model resnet9 --algorithm scaffold --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K10 --model resnet9 --algorithm cadis --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K10 --model resnet9 --algorithm mp_fedavg --wandb 0 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K10 --model resnet9 --algorithm mp_fedprox --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K10 --model resnet9 --algorithm feddyn --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K10 --model resnet9 --algorithm fedadp --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K10 --model resnet9 --algorithm fedfa --alpha 0.5 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K10 --model resnet9 --algorithm fedfv --alpha 0.1 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
# CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K10 --model resnet9 --algorithm fedtest --neg_fct 2 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0

# cifar10_resnet9_clustered_N10_K2 - quantitative
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K2 --model resnet9 --algorithm scaffold --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.2 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K2 --model resnet9 --algorithm cadis --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.2 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K2 --model resnet9 --algorithm mp_fedavg --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.2 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K2 --model resnet9 --algorithm mp_fedprox --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.2 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K2 --model resnet9 --algorithm feddyn --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.2 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K2 --model resnet9 --algorithm fedadp --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.2 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K2 --model resnet9 --algorithm fedfa --alpha 0.5 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.2 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K2 --model resnet9 --algorithm fedfv --alpha 0.1 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.2 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
# CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K2 --model resnet9 --algorithm fedtest --neg_fct 0 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.1 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0

# cifar10_resnet9_clustered_N10_K4 - quantitative
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K4 --model resnet9 --algorithm scaffold --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K4 --model resnet9 --algorithm cadis --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K4 --model resnet9 --algorithm mp_fedavg --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K4 --model resnet9 --algorithm mp_fedprox --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K4 --model resnet9 --algorithm feddyn --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K4 --model resnet9 --algorithm fedadp --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K4 --model resnet9 --algorithm fedfa --alpha 0.5 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K4 --model resnet9 --algorithm fedfv --alpha 0.1 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
# CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K4 --model resnet9 --algorithm fedtest --neg_fct 2 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0

# cifar10_resnet9_clustered_N100_K60 - quantitative
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K6 --model resnet9 --algorithm scaffold --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.6 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K6 --model resnet9 --algorithm cadis --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.6 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K6 --model resnet9 --algorithm mp_fedavg --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.6 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K6 --model resnet9 --algorithm mp_fedprox --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.6 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K6 --model resnet9 --algorithm feddyn --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.6 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K6 --model resnet9 --algorithm fedadp --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.6 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K6 --model resnet9 --algorithm fedfa --alpha 0.5 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.6 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K6 --model resnet9 --algorithm fedfv --alpha 0.1 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.6 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
# CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K6 --model resnet9 --algorithm fedtest --neg_fct 2 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.6 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0

# cifar10_resnet9_clustered_N10_K8 - quantitative
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K8 --model resnet9 --algorithm scaffold --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.8 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K8 --model resnet9 --algorithm cadis --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.8 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K8 --model resnet9 --algorithm mp_fedavg --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.8 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K8 --model resnet9 --algorithm mp_fedprox --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.8 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K8 --model resnet9 --algorithm feddyn --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.8 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K8 --model resnet9 --algorithm fedadp --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.8 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K8 --model resnet9 --algorithm fedfa --alpha 0.5 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.8 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K8 --model resnet9 --algorithm fedfv --alpha 0.1 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.8 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
# CUDA_VISIBLE_DEVICES=0,1 python main.py --task cifar10_resnet9_clustered_N10_K8 --model resnet9 --algorithm fedtest --neg_fct 2 --data_folder "./benchmark/cifar10/data" --log_folder "fedtask" --dataidx_filename "cifar10/cluster/10client/CIFAR10_10client_cluster.json" --num_rounds 500 --num_epochs 5 --proportion 0.8 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
