# CLUSTERED

# mnist_clustered_N100_K20 - quantitative
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_clustered_N100_K20 --model cnn --algorithm fedtest --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/client_cluster/MNIST-100client-cluster-quantitative.json --num_rounds 500 --num_epochs 5 --proportion 0.2 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_clustered_N100_K20 --model cnn --algorithm scaffold --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/client_cluster/MNIST-100client-cluster-quantitative.json --num_rounds 500 --num_epochs 5 --proportion 0.2 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_clustered_N100_K20 --model cnn --algorithm fedsdiv --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/client_cluster/MNIST-100client-cluster-quantitative.json --num_rounds 500 --num_epochs 5 --proportion 0.2 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_clustered_N100_K20 --model cnn --algorithm cadis --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/client_cluster/MNIST-100client-cluster-quantitative.json --num_rounds 500 --num_epochs 5 --proportion 0.2 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_clustered_N100_K20 --model cnn --algorithm fedavg --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/client_cluster/MNIST-100client-cluster-quantitative.json --num_rounds 500 --num_epochs 5 --proportion 0.2 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_clustered_N100_K20 --model cnn --algorithm fedprox --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/client_cluster/MNIST-100client-cluster-quantitative.json --num_rounds 500 --num_epochs 5 --proportion 0.2 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0

# mnist_clustered_N100_K40 - quantitative
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_clustered_N100_K40 --model cnn --algorithm fedtest --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/client_cluster/MNIST-100client-cluster-quantitative.json --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_clustered_N100_K40 --model cnn --algorithm scaffold --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/client_cluster/MNIST-100client-cluster-quantitative.json --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_clustered_N100_K40 --model cnn --algorithm fedsdiv --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/client_cluster/MNIST-100client-cluster-quantitative.json --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_clustered_N100_K40 --model cnn --algorithm cadis --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/client_cluster/MNIST-100client-cluster-quantitative.json --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_clustered_N100_K40 --model cnn --algorithm fedavg --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/client_cluster/MNIST-100client-cluster-quantitative.json --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_clustered_N100_K40 --model cnn --algorithm fedprox --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/client_cluster/MNIST-100client-cluster-quantitative.json --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0

# mnist_clustered_N100_K60 - quantitative
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_clustered_N100_K60 --model cnn --algorithm fedtest --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/client_cluster/MNIST-100client-cluster-quantitative.json --num_rounds 500 --num_epochs 5 --proportion 0.6 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_clustered_N100_K60 --model cnn --algorithm scaffold --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/client_cluster/MNIST-100client-cluster-quantitative.json --num_rounds 500 --num_epochs 5 --proportion 0.6 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_clustered_N100_K60 --model cnn --algorithm fedsdiv --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/client_cluster/MNIST-100client-cluster-quantitative.json --num_rounds 500 --num_epochs 5 --proportion 0.6 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_clustered_N100_K60 --model cnn --algorithm cadis --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/client_cluster/MNIST-100client-cluster-quantitative.json --num_rounds 500 --num_epochs 5 --proportion 0.6 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_clustered_N100_K60 --model cnn --algorithm fedavg --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/client_cluster/MNIST-100client-cluster-quantitative.json --num_rounds 500 --num_epochs 5 --proportion 0.6 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_clustered_N100_K60 --model cnn --algorithm fedprox --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/client_cluster/MNIST-100client-cluster-quantitative.json --num_rounds 500 --num_epochs 5 --proportion 0.6 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0

# mnist_clustered_N100_K80 - quantitative
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_clustered_N100_K80 --model cnn --algorithm fedtest --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/client_cluster/MNIST-100client-cluster-quantitative.json --num_rounds 500 --num_epochs 5 --proportion 0.8 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_clustered_N100_K80 --model cnn --algorithm scaffold --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/client_cluster/MNIST-100client-cluster-quantitative.json --num_rounds 500 --num_epochs 5 --proportion 0.8 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_clustered_N100_K80 --model cnn --algorithm fedsdiv --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/client_cluster/MNIST-100client-cluster-quantitative.json --num_rounds 500 --num_epochs 5 --proportion 0.8 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_clustered_N100_K80 --model cnn --algorithm cadis --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/client_cluster/MNIST-100client-cluster-quantitative.json --num_rounds 500 --num_epochs 5 --proportion 0.8 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_clustered_N100_K80 --model cnn --algorithm fedavg --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/client_cluster/MNIST-100client-cluster-quantitative.json --num_rounds 500 --num_epochs 5 --proportion 0.8 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_clustered_N100_K80 --model cnn --algorithm fedprox --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/client_cluster/MNIST-100client-cluster-quantitative.json --num_rounds 500 --num_epochs 5 --proportion 0.8 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0


# QUANTITATIVE

# mnist_quantitative_N100_K20 
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_quantitative_N100_K20 --model cnn --algorithm fedtest --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/100client/quantitative/60/MNIST-noniid-quantitative_60.json --num_rounds 500 --num_epochs 5 --proportion 0.2 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_quantitative_N100_K20 --model cnn --algorithm scaffold --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/100client/quantitative/60/MNIST-noniid-quantitative_60.json --num_rounds 500 --num_epochs 5 --proportion 0.2 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_quantitative_N100_K20 --model cnn --algorithm cadis --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/100client/quantitative/60/MNIST-noniid-quantitative_60.json --num_rounds 500 --num_epochs 5 --proportion 0.2 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_quantitative_N100_K20 --model cnn --algorithm fedavg --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/100client/quantitative/60/MNIST-noniid-quantitative_60.json --num_rounds 500 --num_epochs 5 --proportion 0.2 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_quantitative_N100_K20 --model cnn --algorithm fedprox --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/100client/quantitative/60/MNIST-noniid-quantitative_60.json --num_rounds 500 --num_epochs 5 --proportion 0.2 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0

# mnist_quantitative_N100_K40 
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_quantitative_N100_K40 --model cnn --algorithm fedtest --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/100client/quantitative/60/MNIST-noniid-quantitative_60.json --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_quantitative_N100_K40 --model cnn --algorithm scaffold --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/100client/quantitative/60/MNIST-noniid-quantitative_60.json --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_quantitative_N100_K40 --model cnn --algorithm cadis --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/100client/quantitative/60/MNIST-noniid-quantitative_60.json --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_quantitative_N100_K40 --model cnn --algorithm fedavg --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/100client/quantitative/60/MNIST-noniid-quantitative_60.json --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_quantitative_N100_K40 --model cnn --algorithm fedprox --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/100client/quantitative/60/MNIST-noniid-quantitative_60.json --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0

# mnist_quantitative_N100_K60 
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_quantitative_N100_K60 --model cnn --algorithm fedtest --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/100client/quantitative/60/MNIST-noniid-quantitative_60.json --num_rounds 500 --num_epochs 5 --proportion 0.6 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_quantitative_N100_K60 --model cnn --algorithm scaffold --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/100client/quantitative/60/MNIST-noniid-quantitative_60.json --num_rounds 500 --num_epochs 5 --proportion 0.6 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_quantitative_N100_K60 --model cnn --algorithm cadis --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/100client/quantitative/60/MNIST-noniid-quantitative_60.json --num_rounds 500 --num_epochs 5 --proportion 0.6 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_quantitative_N100_K60 --model cnn --algorithm fedavg --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/100client/quantitative/60/MNIST-noniid-quantitative_60.json --num_rounds 500 --num_epochs 5 --proportion 0.6 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_quantitative_N100_K60 --model cnn --algorithm fedprox --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/100client/quantitative/60/MNIST-noniid-quantitative_60.json --num_rounds 500 --num_epochs 5 --proportion 0.6 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0

# mnist_quantitative_N100_K80 
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_quantitative_N100_K80 --model cnn --algorithm fedtest --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/100client/quantitative/60/MNIST-noniid-quantitative_60.json --num_rounds 500 --num_epochs 5 --proportion 0.8 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_quantitative_N100_K80 --model cnn --algorithm scaffold --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/100client/quantitative/60/MNIST-noniid-quantitative_60.json --num_rounds 500 --num_epochs 5 --proportion 0.8 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_quantitative_N100_K80 --model cnn --algorithm cadis --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/100client/quantitative/60/MNIST-noniid-quantitative_60.json --num_rounds 500 --num_epochs 5 --proportion 0.8 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_quantitative_N100_K80 --model cnn --algorithm fedavg --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/100client/quantitative/60/MNIST-noniid-quantitative_60.json --num_rounds 500 --num_epochs 5 --proportion 0.8 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_quantitative_N100_K80 --model cnn --algorithm fedprox --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/100client/quantitative/60/MNIST-noniid-quantitative_60.json --num_rounds 500 --num_epochs 5 --proportion 0.8 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0


# FEATURED

# mnist_featured_N100_K20
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_featured_N100_K20 --model cnn --algorithm fedtest --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/100client/featured/60/MNIST-noniid-featured_60.json --num_rounds 500 --num_epochs 5 --proportion 0.2 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_featured_N100_K20 --model cnn --algorithm scaffold --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/100client/featured/60/MNIST-noniid-featured_60.json --num_rounds 500 --num_epochs 5 --proportion 0.2 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_featured_N100_K20 --model cnn --algorithm cadis --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/100client/featured/60/MNIST-noniid-featured_60.json --num_rounds 500 --num_epochs 5 --proportion 0.2 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_featured_N100_K20 --model cnn --algorithm fedavg --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/100client/featured/60/MNIST-noniid-featured_60.json --num_rounds 500 --num_epochs 5 --proportion 0.2 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_featured_N100_K20 --model cnn --algorithm fedprox --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/100client/featured/60/MNIST-noniid-featured_60.json --num_rounds 500 --num_epochs 5 --proportion 0.2 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0

# mnist_featured_N100_K40
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_featured_N100_K40 --model cnn --algorithm fedtest --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/100client/featured/60/MNIST-noniid-featured_60.json --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_featured_N100_K40 --model cnn --algorithm scaffold --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/100client/featured/60/MNIST-noniid-featured_60.json --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_featured_N100_K40 --model cnn --algorithm cadis --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/100client/featured/60/MNIST-noniid-featured_60.json --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_featured_N100_K40 --model cnn --algorithm fedavg --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/100client/featured/60/MNIST-noniid-featured_60.json --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_featured_N100_K40 --model cnn --algorithm fedprox --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/100client/featured/60/MNIST-noniid-featured_60.json --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0

# mnist_featured_N100_K60
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_featured_N100_K60 --model cnn --algorithm fedtest --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/100client/featured/60/MNIST-noniid-featured_60.json --num_rounds 500 --num_epochs 5 --proportion 0.6 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_featured_N100_K60 --model cnn --algorithm scaffold --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/100client/featured/60/MNIST-noniid-featured_60.json --num_rounds 500 --num_epochs 5 --proportion 0.6 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_featured_N100_K60 --model cnn --algorithm cadis --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/100client/featured/60/MNIST-noniid-featured_60.json --num_rounds 500 --num_epochs 5 --proportion 0.6 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_featured_N100_K60 --model cnn --algorithm fedavg --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/100client/featured/60/MNIST-noniid-featured_60.json --num_rounds 500 --num_epochs 5 --proportion 0.6 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_featured_N100_K60 --model cnn --algorithm fedprox --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/100client/featured/60/MNIST-noniid-featured_60.json --num_rounds 500 --num_epochs 5 --proportion 0.6 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0

# mnist_featured_N100_K80
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_featured_N100_K80 --model cnn --algorithm fedtest --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/100client/featured/60/MNIST-noniid-featured_60.json --num_rounds 500 --num_epochs 5 --proportion 0.8 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_featured_N100_K80 --model cnn --algorithm scaffold --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/100client/featured/60/MNIST-noniid-featured_60.json --num_rounds 500 --num_epochs 5 --proportion 0.8 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_featured_N100_K80 --model cnn --algorithm cadis --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/100client/featured/60/MNIST-noniid-featured_60.json --num_rounds 500 --num_epochs 5 --proportion 0.8 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_featured_N100_K80 --model cnn --algorithm fedavg --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/100client/featured/60/MNIST-noniid-featured_60.json --num_rounds 500 --num_epochs 5 --proportion 0.8 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_featured_N100_K80 --model cnn --algorithm fedprox --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/100client/featured/60/MNIST-noniid-featured_60.json --num_rounds 500 --num_epochs 5 --proportion 0.8 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0


# PARETO

# mnist_pareto_N100_K20
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_pareto_N100_K20 --model cnn --algorithm fedtest --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/100client/pareto/MNIST-noniid-pareto_1.json --num_rounds 500 --num_epochs 5 --proportion 0.2 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_pareto_N100_K20 --model cnn --algorithm scaffold --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/100client/pareto/MNIST-noniid-pareto_1.json --num_rounds 500 --num_epochs 5 --proportion 0.2 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_pareto_N100_K20 --model cnn --algorithm cadis --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/100client/pareto/MNIST-noniid-pareto_1.json --num_rounds 500 --num_epochs 5 --proportion 0.2 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_pareto_N100_K20 --model cnn --algorithm fedavg --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/100client/pareto/MNIST-noniid-pareto_1.json --num_rounds 500 --num_epochs 5 --proportion 0.2 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_pareto_N100_K20 --model cnn --algorithm fedprox --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/100client/pareto/MNIST-noniid-pareto_1.json --num_rounds 500 --num_epochs 5 --proportion 0.2 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0

# mnist_pareto_N100_K40
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_pareto_N100_K40 --model cnn --algorithm fedtest --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/100client/pareto/MNIST-noniid-pareto_1.json --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_pareto_N100_K40 --model cnn --algorithm scaffold --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/100client/pareto/MNIST-noniid-pareto_1.json --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_pareto_N100_K40 --model cnn --algorithm cadis --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/100client/pareto/MNIST-noniid-pareto_1.json --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_pareto_N100_K40 --model cnn --algorithm fedavg --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/100client/pareto/MNIST-noniid-pareto_1.json --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_pareto_N100_K40 --model cnn --algorithm fedprox --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/100client/pareto/MNIST-noniid-pareto_1.json --num_rounds 500 --num_epochs 5 --proportion 0.4 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0

# mnist_pareto_N100_K60
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_pareto_N100_K60 --model cnn --algorithm fedtest --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/100client/pareto/MNIST-noniid-pareto_1.json --num_rounds 500 --num_epochs 5 --proportion 0.6 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_pareto_N100_K60 --model cnn --algorithm scaffold --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/100client/pareto/MNIST-noniid-pareto_1.json --num_rounds 500 --num_epochs 5 --proportion 0.6 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_pareto_N100_K60 --model cnn --algorithm cadis --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/100client/pareto/MNIST-noniid-pareto_1.json --num_rounds 500 --num_epochs 5 --proportion 0.6 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_pareto_N100_K60 --model cnn --algorithm fedavg --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/100client/pareto/MNIST-noniid-pareto_1.json --num_rounds 500 --num_epochs 5 --proportion 0.6 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_pareto_N100_K60 --model cnn --algorithm fedprox --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/100client/pareto/MNIST-noniid-pareto_1.json --num_rounds 500 --num_epochs 5 --proportion 0.6 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0

# mnist_pareto_N100_K80
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_pareto_N100_K80 --model cnn --algorithm fedtest --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/100client/pareto/MNIST-noniid-pareto_1.json --num_rounds 500 --num_epochs 5 --proportion 0.8 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_pareto_N100_K80 --model cnn --algorithm scaffold --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/100client/pareto/MNIST-noniid-pareto_1.json --num_rounds 500 --num_epochs 5 --proportion 0.8 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_pareto_N100_K80 --model cnn --algorithm cadis --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/100client/pareto/MNIST-noniid-pareto_1.json --num_rounds 500 --num_epochs 5 --proportion 0.8 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_pareto_N100_K80 --model cnn --algorithm fedavg --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/100client/pareto/MNIST-noniid-pareto_1.json --num_rounds 500 --num_epochs 5 --proportion 0.8 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_pareto_N100_K80 --model cnn --algorithm fedprox --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/100client/pareto/MNIST-noniid-pareto_1.json --num_rounds 500 --num_epochs 5 --proportion 0.8 --batch_size 8 --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0

