mkdir fedtask

# mnist_featured_N10_K10 - featured
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_featured_N10_K10 --model cnn --algorithm fedtest --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/featured/MNIST-noniid-featured_1.json --num_rounds 500 --num_epochs 5 --learning_rate 0.001 --proportion 1 --batch_size 8  --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_featured_N10_K10 --model cnn --algorithm scaffold --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/featured/MNIST-noniid-featured_1.json --num_rounds 500 --num_epochs 5 --learning_rate 0.001 --proportion 1 --batch_size 8  --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_featured_N10_K10 --model cnn --algorithm cadis --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/featured/MNIST-noniid-featured_1.json --num_rounds 500 --num_epochs 5 --learning_rate 0.001 --proportion 1 --batch_size 8  --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_featured_N10_K10 --model cnn --algorithm mp_fedavg --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/featured/MNIST-noniid-featured_1.json --num_rounds 500 --num_epochs 5 --learning_rate 0.001 --proportion 1 --batch_size 8  --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_featured_N10_K10 --model cnn --algorithm mp_fedprox --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/featured/MNIST-noniid-featured_1.json --num_rounds 500 --num_epochs 5 --learning_rate 0.001 --proportion 1 --batch_size 8  --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0

# mnist_pareto_N10_K10 - pareto
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_pareto_N10_K10 --model cnn --algorithm fedtest --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/pareto/MNIST-noniid-fedavg_pareto_1.json --num_rounds 500 --num_epochs 5 --learning_rate 0.001 --proportion 1 --batch_size 8  --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_pareto_N10_K10 --model cnn --algorithm scaffold --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/pareto/MNIST-noniid-fedavg_pareto_1.json --num_rounds 500 --num_epochs 5 --learning_rate 0.001 --proportion 1 --batch_size 8  --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_pareto_N10_K10 --model cnn --algorithm cadis --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/pareto/MNIST-noniid-fedavg_pareto_1.json --num_rounds 500 --num_epochs 5 --learning_rate 0.001 --proportion 1 --batch_size 8  --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_pareto_N10_K10 --model cnn --algorithm mp_fedavg --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/pareto/MNIST-noniid-fedavg_pareto_1.json --num_rounds 500 --num_epochs 5 --learning_rate 0.001 --proportion 1 --batch_size 8  --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_pareto_N10_K10 --model cnn --algorithm mp_fedprox --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/pareto/MNIST-noniid-fedavg_pareto_1.json --num_rounds 500 --num_epochs 5 --learning_rate 0.001 --proportion 1 --batch_size 8  --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0

# mnist_quantitative_N10_K10 - quantitative
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_quantitative_N10_K10 --model cnn --algorithm fedtest --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/quantitative/MNIST-noniid-quantitative_1.json --num_rounds 500 --num_epochs 5 --learning_rate 0.001 --proportion 1 --batch_size 8  --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_quantitative_N10_K10 --model cnn --algorithm scaffold --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/quantitative/MNIST-noniid-quantitative_1.json --num_rounds 500 --num_epochs 5 --learning_rate 0.001 --proportion 1 --batch_size 8  --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_quantitative_N10_K10 --model cnn --algorithm cadis --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/quantitative/MNIST-noniid-quantitative_1.json --num_rounds 500 --num_epochs 5 --learning_rate 0.001 --proportion 1 --batch_size 8  --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_quantitative_N10_K10 --model cnn --algorithm mp_fedavg --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/quantitative/MNIST-noniid-quantitative_1.json --num_rounds 500 --num_epochs 5 --learning_rate 0.001 --proportion 1 --batch_size 8  --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
CUDA_VISIBLE_DEVICES=0,1 python main.py --task mnist_quantitative_N10_K10 --model cnn --algorithm mp_fedprox --data_folder ./benchmark/mnist/data --log_folder fedtask --dataidx_filename mnist/quantitative/MNIST-noniid-quantitative_1.json --num_rounds 500 --num_epochs 5 --learning_rate 0.001 --proportion 1 --batch_size 8  --num_threads_per_gpu 2  --num_gpus 2 --server_gpu_id 0
